POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "John2",
  "lastName": "Doe2",
  "username": "johndoe2",
  "password": "password"
}

###

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "password"
}

###
POST http://localhost:8080/api/v1/user/preferences/set
Authorization: Bearer eyJraWQiOiJmN2I4NjQyMi0wNTgxLTQzNmMtOTRlMC1kN2M0MTNhNWRkYjAiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiam9obmRvZSIsImV4cCI6MTcxMzg2ODU0NSwiaWF0IjoxNzExMTkwMTQ1LCJzY29wZSI6IlJPTEVfVVNFUiJ9.EN_XOEqKzaazhtwrdJrbLzG7UTn651ecsbSaGZJJkL6356SB3Y5-SSxAFwxD_HZQ6DafomY8GBfYAoxWECEC-2I6BLGm3lB7gjrZtniScobV7fJOxw8_kQtKiMga5yVCwjOj_MSfIh_HddseJWgyXaP-yM9nsvakLKL6tS-3ZRgK6HCC9AMCv1c_BuZ7lmTZU2XT5SPMGMgStSa9DW7nCxdf7PEcRXDhGZXyJ3kWB5482fZOZnYuU8yIylHXnu8AbzzOXR5okyLuNX6xE0tCR_SYV4k1kSkL-sr8dBqlW5aaQJ8SCwcugWlGDS6EbeDBmdiTgs9j4SeaSb4RqL3tPw
Content-Type: application/json

{
  "minAge": 11,
  "maxAge": 40,
  "preferences": ["Programming"]
}

###

POST http://localhost:8080/api/v1/user/match
Authorization: Bearer eyJraWQiOiIwZDdkZjNlYy00YmQ5LTQ4MDEtODM4NS1lODhiYTgwOGY4ZjgiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiam9obmRvZSIsImV4cCI6MTcxMzg2ODgyNCwiaWF0IjoxNzExMTkwNDI0LCJzY29wZSI6IlJPTEVfVVNFUiJ9.XMm1_0WkXux2p5ja13SxM2LvUkjw8gc12KRiz1mlB51PPV9mR5xTmh6cdsVjEQ9zWknLUBuJPxvv6jS633JWHEf_NrAQs-of_6ikUBvK57pkES1Puo3tLs3Hrmd87fx_zz7_PbEGRmb1Nj1NdQ9kbRW5g1WaiR0UGXbyrzTAC98vnp7C68BDqPB21glWgkpgnZBCENcA2uCuPm4M94BcxOfW7HW5CmXXj768UuLZLOiYcqXpPx6sBy07RciOXXhS1TQGHDuAUCbn36k5xc9tTw2hUyHC63SwoolXQpEyePD6Hh9BWLUKGBEucfsUiq4eF7IwjRuYyIgdCQ5WaBqCHg
Content-Type: application/json

{
  "mentorUsername": "johndoe2"
}
